### ISSUE TITLE
Not able to get insight from go-sdk

### ISSUE THREAD

**Issue by shristygupta26** [featbit/featbit-go-sdk#3]
I am using feature flag functionality from go-sdk
`"github.com/featbit/featbit-go-sdk"`
`"github.com/featbit/featbit-go-sdk/interfaces"`

 I am using go `version go1.18.1` darwin/arm64

I wrote the following code which is a simple toggle switch
<img width="1098" alt="Screenshot 2023-03-06 at 4 49 25 PM" src="https://user-images.githubusercontent.com/108508500/223105820-7aac8883-c4c3-4ea8-a388-f46f5efd4a11.png">

```go
func main() {
	client, err := featbit.NewFBClient(envSecret, streamingUrl, eventUrl)
	if err != nil {
		// error handle
		panic(err)
	}
	user, err := interfaces.NewUserBuilder("my-user").UserName("my-user").Custom("role", "logged-in").Build()
	if err != nil {
		// error handle
		panic(err)

	}
	// be sure that SDK is initialized
	// this is not required
	if client.IsInitialized() {
		// Flag value
		// returns a bool variation
		if res, _, err := client.BoolVariation("test-feature", user, false); res {
			if err != nil {
				// error handle
				panic(err)
			}
			fmt.Printf("Test User is active and feature is released")

		} else {
			fmt.Printf("Test User is deactive and feature is not released")
		}
	}
}
```

But the same logic I ran for Javascript and got insights. 
<img width="730" alt="Screenshot 2023-03-06 at 5 30 47 PM" src="https://user-images.githubusercontent.com/108508500/223105959-247aba5d-38ca-4374-9464-45c302d4fdb5.png">

Kindly help and do the needful! Also let me know if you need more reference. https://featbit.slack.com/archives/C0402K5S8KV/p1678100930239479

**Comment by deleteLater** [comment]
The insight was sent asynchronously. In the example code above, the app will exit before the insight was sent out. To ensure that all insights are sent out before the app exits, add `_ = client.Close()` at the end of the main function. This should resolve the problem.
